name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12h
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: JpGomes035
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar animação no branch "output"
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
